version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amis_properties
    ports:
      - "5432:5432"
    volumes:
      - amis_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - ./uploads:/app/uploads

volumes:
  amis_pg_data:
